# ===================================================
# Generated for R2dbcExtensionAutoConfiguration
# ===================================================

# ?????? Registrar ????? Bean ???????
com.jxpanda.autoconfigure.R2dbcExtensionAutoConfiguration.BeanNames=\
testReactiveService,test2ReactiveService

# ????????? Bean ?????????????
com.jxpanda.autoconfigure.R2dbcExtensionAutoConfiguration.BeanTypes=\
reactiveEntityService<Test>
