spring:
  main:
    allow-bean-definition-overriding: true

panda:
  r2dbc:
    url: r2dbc:pool:pool:mysql://mysql.jxpanda.com:2333/hydrogen
    username: root
    password: Root2021@)@!
    mapping:
      force-quote: true
      entity:
        naming-policy: camel_case_to_snake_case
#logging:
#  level:
#    root: debug