spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: database


panda:
  r2dbc:
    mapping:
      validation-strategy: NOT_EMPTY
      naming-strategy: CAMEL_CASE_TO_SNAKE_CASE
    database:
      id-strategy: USE_GENERATOR
      force-quote: false
    plugin:
      logic-delete:
        enable: true
        field: deleted_time
        value:
          type: DATE_TIME




logging:
  level:
    root: INFO