spring:
  main:
    allow-bean-definition-overriding: true

panda:
  r2dbc:
    url: r2dbc:pool:pool:mysql://mysql.ynjunke.cn:32333/hydrogen
    username: root
    password: Root2021@)@!

#logging:
#  level:
#    root: debug