spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:pool:mysql://mysql.jxpanda.com:2333/hydrogen
    username: root
    password: Root2021@)@!



panda:
  r2dbc:
    force-quote: true
    validation-policy: NOT_EMPTY
    naming-policy: CAMEL_CASE_TO_SNAKE_CASE
    logic-delete:
      enable: true
      undelete-value: 1970-01-01 00:00:00
      delete-value: CURRENT_TIMESTAMP
      field: deleted_date


#logging:
#  level:
#    root: debug