spring:
  main:
    allow-bean-definition-overriding: true

panda:
  r2dbc:
    url: r2dbc:pool:pool:mysql://mysql.jxpanda.com:2333/hydrogen
    username: root
    password: Root2021@)@!
    mapping-properties:
      force-quote: true
      validation-policy: NOT_EMPTY
      naming-policy: CAMEL_CASE_TO_SNAKE_CASE


#logging:
#  level:
#    root: debug